AllCops:
  Includes:
    - metadata.rb
    - Gemfile
    - attributes/**
    - recipes/**
    - spec/**
    - libraries/**
  Excludes:
    - providers/**
    - resources/**

Encoding:
  Exclude:
    - metadata.rb
    - Gemfile

LineLength:
  Enabled: false

WordArray:
  MinSize: 3
